table dates
	lineageTag: 29f86b34-2434-4f40-9e10-2caf41fcc2f1

	column date_id
		dataType: int64
		formatString: 0
		lineageTag: 37c15f23-1447-498b-926c-9f946a515d50
		summarizeBy: none
		sourceColumn: date_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: a41f6433-1d91-46ed-a1cf-25088c1090be
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 0cfc38c3-364d-484b-af86-c811e9a31b33
			defaultHierarchy: LocalDateTable_499096b7-49fa-4269-b315-d9804b837955.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column date_month
		dataType: int64
		formatString: 0
		lineageTag: 9b96ffd4-3f93-4524-b21c-7caadf44d5a5
		summarizeBy: sum
		sourceColumn: date_month

		annotation SummarizationSetBy = Automatic

	column date_day
		dataType: int64
		formatString: 0
		lineageTag: 13efa438-ecff-4d66-bb42-d2e5b2344cad
		summarizeBy: sum
		sourceColumn: date_day

		annotation SummarizationSetBy = Automatic

	column date_weekday
		dataType: string
		lineageTag: 2d5bd8a2-02d1-4f96-843d-0c9ac06acc42
		summarizeBy: none
		sourceColumn: date_weekday

		annotation SummarizationSetBy = Automatic

	column date_week
		dataType: int64
		formatString: 0
		lineageTag: 3e643a7e-9eaa-4025-8caf-329542cff104
		summarizeBy: sum
		sourceColumn: date_week

		annotation SummarizationSetBy = Automatic

	partition dates = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\vongp\Desktop\Programming\PowerBI\dates.csv"),[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"date_id", Int64.Type}, {"date", type date}, {"date_month", Int64.Type}, {"date_day", Int64.Type}, {"date_weekday", type text}, {"date_week", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

