table products
	lineageTag: 7b34ee0f-f9ac-4ffb-98ea-dbe94942a1c2

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: b572d74b-2a1e-47e2-9df7-e63edf575ea4
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column product_name
		dataType: string
		lineageTag: fd91003f-2be4-4ea1-bbbf-1bc7cb875be5
		summarizeBy: none
		sourceColumn: product_name

		annotation SummarizationSetBy = Automatic

	column product_category
		dataType: string
		lineageTag: b388d594-1568-4e9e-ab36-9e5cbfda836f
		summarizeBy: none
		sourceColumn: product_category

		annotation SummarizationSetBy = Automatic

	column product_brand
		dataType: string
		lineageTag: c92b7ffe-d47d-4bd0-b6f5-6658890eda45
		summarizeBy: none
		sourceColumn: product_brand

		annotation SummarizationSetBy = Automatic

	column product_model
		dataType: string
		lineageTag: 9ed9ed80-61aa-4687-af29-eae68fa6baed
		summarizeBy: none
		sourceColumn: product_model

		annotation SummarizationSetBy = Automatic

	column product_list_price
		dataType: double
		lineageTag: 78b676a1-ffee-4300-b1d9-aa94d5d9bd46
		summarizeBy: none
		sourceColumn: product_list_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column product_standard_cost
		dataType: double
		lineageTag: 852d2231-003e-4223-9c9a-b1d3b407b6a4
		summarizeBy: none
		sourceColumn: product_standard_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column product_is_active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4074896c-c83c-47e4-b95e-29f3874adb2a
		summarizeBy: none
		sourceColumn: product_is_active

		annotation SummarizationSetBy = Automatic

	partition products = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\vongp\Desktop\Programming\PowerBI\products.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"product_id", Int64.Type}, {"product_name", type text}, {"product_category", type text}, {"product_brand", type text}, {"product_model", type text}, {"product_list_price", type number}, {"product_standard_cost", type number}, {"product_is_active", type logical}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

